name: Sign and Verify

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 22.0

      - name: clean maven package
        run: mvn clean package
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: check target folder
        run: cd target && cd classes && cd org && cd example && ls -a

#      - name: Run SignArtifact from JAR
#        run: java -jar target/ghactions-oidc-sigstore-1.0-SNAPSHOT.jar